const CHANGE_NAME = 'CHANGE_NAME';
const CHANGE_EMAIL = 'CHANGE_EMAIL';
const CHANGE_CITY = 'CHANGE_CITY';
const CHANGE_SUGGESTIONS_CITIES = 'CHANGE_SUGGESTIONS_CITIES';
const CHANGE_STATE = 'CHANGE_STATE';
const CHANGE_COUNTRY = 'CHANGE_COUNTRY';
const CHANGE_AGE = 'CHANGE_AGE';
const CHANGE_LOGIN = 'CHANGE_LOGIN';
const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
const CHANGE_SECURE = 'CHANGE_SECURE';
const CHANGE_CONFIRM_PASSWORD = 'CHANGE_CONFIRM_PASSWORD';

export default {
  CHANGE_NAME,
  CHANGE_EMAIL,
  CHANGE_CITY,
  CHANGE_SUGGESTIONS_CITIES,
  CHANGE_STATE,
  CHANGE_COUNTRY,
  CHANGE_AGE,
  CHANGE_LOGIN,
  CHANGE_PASSWORD,
  CHANGE_SECURE,
  CHANGE_CONFIRM_PASSWORD,
};
